FROM ghcr.io/whynotea/devcontainer-base:v1.0.2

USER root

RUN dnf -y update && \
  dnf install --setopt=install_weak_deps=false --setopt=tsflags=nodocs -y\
    cmake cppcheck valgrind gdb libXinerama-devel libstdc++-static && \
  dnf groupinstall --setopt=install_weak_deps=false --setopt=tsflags=nodocs -y\
    "X Software Development"

# Setup ENV vars for vcpkg
ENV VCPKG_ROOT=/usr/local/vcpkg \
  VCPKG_DOWNLOADS=/usr/local/vcpkg-downloads
ENV PATH="${PATH}:${VCPKG_ROOT}"

ARG USERNAME=code

COPY base-scripts/install-vcpkg.sh /tmp/
RUN chmod +x /tmp/install-vcpkg.sh \
  && /tmp/install-vcpkg.sh ${USERNAME} \
  && rm -f /tmp/install-vcpkg.sh

USER code
